import sys

if len (sys.argv) != 2:
    print ("Usage: {0} <filename>".format (sys.argv[0]))
    sys.exit (1)

clname = sys.argv[1]
import re

# word = 'hello;'

# print (word.find('o'))

with open (clname) as file_in:
    lines = file_in.readlines()
    lastSplit = -1
    for i in range (0, len(lines)):
        print (lines[i], end='')

        if 'split' in lines[i]:
            words = lines[i].split(' ')
            nums = words[len(words)-1].split(';')
            n = nums[0]
            if (n == '63'):
                print ('(* generated by python *)')
                carryOut = words[1]
                for j in range (i-1, lastSplit, -1):
                    if 'adds' in lines[j]:
                        words = lines[j].split(' ')
                        sumOut = words[2]
                        adden1 = words[3]
                        adden2 = words[4][0:words[4].find(';')]
                        # print ('{0}, {1}, {2}'.format(sumOut, adden1, adden2))
                        hasThreeOp = False
                        for k in range (j, lastSplit, -1):
                            if 'adds' in lines[k]:
                                words = lines[k].split(' ')
                                target = words[2]
                                if target == adden1:
                                    hasThreeOp = True
                                    adden3 = adden2
                                    adden1 = words[3]
                                    adden2 = words[4][0:words[4].find(';')]
                                    break
                                elif target == adden2:
                                    hasThreeOp = True
                                    adden2 = words[3]
                                    adden3 = words[4][0:words[4].find(';')]
                                    break
                        if hasThreeOp:
                            print ("assert true && limbs 64 [{0}, {1}] = limbs 64 [{2}, 0@64] + limbs 64 [{3}, 0@64] + limbs 64 [{4}, 0@64];".
                                   format(sumOut, carryOut, adden1, adden2, adden3))
                            print ("assume limbs 64 [{0}, {1}] = limbs 64 [{2}, 0] + limbs 64 [{3}, 0] + limbs 64 [{4}, 0] && true;".
                                   format(sumOut, carryOut, adden1, adden2, adden3))
                        else:
                            print ("assert true && limbs 64 [{0}, {1}] = limbs 64 [{2}, 0@64] + limbs 64 [{3}, 0@64];".
                                   format(sumOut, carryOut, adden1, adden2))
                            print ("assume limbs 64 [{0}, {1}] = limbs 64 [{2}, 0] + limbs 64 [{3}, 0] && true;".
                                   format(sumOut, carryOut, adden1, adden2))

                        break
                            
                lastSplit = i

        # else:
            # do nothing
                        

